### Create a new user OK
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "a@a.com",
    "password": "123"
}

### Create a new user ERROR
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "a@a",
    "password": 123
}
