### Create a new user OK
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "a@a.com",
    "password": "123"
}

### Create a new user ERROR
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "a@a",
    "password": 123
}

### Find a particular user with a given ID OK
GET http://localhost:3000/auth/1

### Find all users with a given email OK
GET http://localhost:3000/auth?email=a@a.com

### Delete a user with a given ID
DELETE http://localhost:3000/auth/14
